// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ShaderTools.Editor.VisualStudio
{
    static class Vsix
    {
        public const string Id = "7def6c01-a05e-42e6-953d-3fdea1891737";
        public const string Name = "HLSL Tools for Visual Studio";
        public const string Description = @"Enhanced support for editing HLSL in Visual Studio";
        public const string Language = "en-US";
        public const string Version = "1.1.300";
        public const string Author = "Tim Jones";
        public const string Tags = "HLSL, shader, Direct3D";
    }
}
