//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShaderTools.CodeAnalysis.Editor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EditorFeaturesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EditorFeaturesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShaderTools.CodeAnalysis.Editor.Properties.EditorFeaturesResources", typeof(EditorFeaturesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment Selection.
        /// </summary>
        internal static string Comment_Selection {
            get {
                return ResourceManager.GetString("Comment_Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commenting currently selected text....
        /// </summary>
        internal static string Commenting_currently_selected_text {
            get {
                return ResourceManager.GetString("Commenting_currently_selected_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transaction is already complete..
        /// </summary>
        internal static string The_transaction_is_already_complete {
            get {
                return ResourceManager.GetString("The_transaction_is_already_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncomment Selection.
        /// </summary>
        internal static string Uncomment_Selection {
            get {
                return ResourceManager.GetString("Uncomment_Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncommenting currently selected text....
        /// </summary>
        internal static string Uncommenting_currently_selected_text {
            get {
                return ResourceManager.GetString("Uncommenting_currently_selected_text", resourceCulture);
            }
        }
    }
}
