//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShaderTools.CodeAnalysis.Hlsl.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShaderTools.CodeAnalysis.Hlsl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary operator &apos;{0}&apos; invocation on types &apos;{1}&apos; and &apos;{2}&apos; is ambiguous..
        /// </summary>
        internal static string AmbiguousBinaryOperator {
            get {
                return ResourceManager.GetString("AmbiguousBinaryOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; is ambiguous..
        /// </summary>
        internal static string AmbiguousField {
            get {
                return ResourceManager.GetString("AmbiguousField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invocation is ambiguous between &apos;{0}&apos; and &apos;{1}&apos;..
        /// </summary>
        internal static string AmbiguousInvocation {
            get {
                return ResourceManager.GetString("AmbiguousInvocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is ambiguous between &apos;{1}&apos; and &apos;{2}&apos;..
        /// </summary>
        internal static string AmbiguousNamespaceOrType {
            get {
                return ResourceManager.GetString("AmbiguousNamespaceOrType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name &apos;{0}&apos; is ambiguous between &apos;{1}&apos; and &apos;{2}&apos;..
        /// </summary>
        internal static string AmbiguousReference {
            get {
                return ResourceManager.GetString("AmbiguousReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; is ambiguous between &apos;{1}&apos; and &apos;{2}&apos;..
        /// </summary>
        internal static string AmbiguousType {
            get {
                return ResourceManager.GetString("AmbiguousType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unary operator &apos;{0}&apos; invocation on type &apos;{1}&apos; is ambiguous..
        /// </summary>
        internal static string AmbiguousUnaryOperator {
            get {
                return ResourceManager.GetString("AmbiguousUnaryOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preprocessor directives must appear as the first non-whitespace character on a line..
        /// </summary>
        internal static string BadDirectivePlacement {
            get {
                return ResourceManager.GetString("BadDirectivePlacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embedded statement cannot be a declaration..
        /// </summary>
        internal static string BadEmbeddedStatement {
            get {
                return ResourceManager.GetString("BadEmbeddedStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot apply binary operator &apos;{0}&apos; on types &apos;{1}&apos; and &apos;{2}&apos;..
        /// </summary>
        internal static string CannotApplyBinaryOperator {
            get {
                return ResourceManager.GetString("CannotApplyBinaryOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot apply unary operator &apos;{0}&apos; on type &apos;{1}&apos;..
        /// </summary>
        internal static string CannotApplyUnaryOperator {
            get {
                return ResourceManager.GetString("CannotApplyUnaryOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert type &apos;{0}&apos; to &apos;{1}&apos;..
        /// </summary>
        internal static string CannotConvert {
            get {
                return ResourceManager.GetString("CannotConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A constant value is expected..
        /// </summary>
        internal static string ConstantExpected {
            get {
                return ResourceManager.GetString("ConstantExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preprocessor directive expected..
        /// </summary>
        internal static string DirectiveExpected {
            get {
                return ResourceManager.GetString("DirectiveExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected #endif directive..
        /// </summary>
        internal static string EndIfDirectiveExpected {
            get {
                return ResourceManager.GetString("EndIfDirectiveExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment or end-of-line expected..
        /// </summary>
        internal static string EndOfPreprocessorLineExpected {
            get {
                return ResourceManager.GetString("EndOfPreprocessorLineExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected expression..
        /// </summary>
        internal static string ExpressionExpected {
            get {
                return ResourceManager.GetString("ExpressionExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function &apos;{0}&apos; missing implementation..
        /// </summary>
        internal static string FunctionMissingImplementation {
            get {
                return ResourceManager.GetString("FunctionMissingImplementation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No overload for &apos;{0}&apos; takes {1} arguments..
        /// </summary>
        internal static string FunctionOverloadResolutionFailure {
            get {
                return ResourceManager.GetString("FunctionOverloadResolutionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character in input &apos;{0}&apos;..
        /// </summary>
        internal static string IllegalInputCharacter {
            get {
                return ResourceManager.GetString("IllegalInputCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implicit truncation from &apos;{0}&apos; to &apos;{1}&apos;..
        /// </summary>
        internal static string ImplicitTruncation {
            get {
                return ResourceManager.GetString("ImplicitTruncation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open source file &apos;{0}&apos;..
        /// </summary>
        internal static string IncludeNotFound {
            get {
                return ResourceManager.GetString("IncludeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error opening source file &apos;{0}&apos;: {1}..
        /// </summary>
        internal static string IncludeUnexpectedError {
            get {
                return ResourceManager.GetString("IncludeUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character literal..
        /// </summary>
        internal static string InvalidCharacterLiteral {
            get {
                return ResourceManager.GetString("InvalidCharacterLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid expression term &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidExprTerm {
            get {
                return ResourceManager.GetString("InvalidExprTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid hex number..
        /// </summary>
        internal static string InvalidHex {
            get {
                return ResourceManager.GetString("InvalidHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text &apos;{0}&apos; is not a valid identifier.
        /// </summary>
        internal static string InvalidIdentifier {
            get {
                return ResourceManager.GetString("InvalidIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid integer..
        /// </summary>
        internal static string InvalidInteger {
            get {
                return ResourceManager.GetString("InvalidInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid octal number..
        /// </summary>
        internal static string InvalidOctal {
            get {
                return ResourceManager.GetString("InvalidOctal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid decimal number..
        /// </summary>
        internal static string InvalidReal {
            get {
                return ResourceManager.GetString("InvalidReal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invocation of &apos;{0}&apos; requires parenthesis..
        /// </summary>
        internal static string InvocationRequiresParenthesis {
            get {
                return ResourceManager.GetString("InvocationRequiresParenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop control variable &apos;{0}&apos; conflicts with a previous declaration in the outer scope. The most recent declaration will be used..
        /// </summary>
        internal static string LoopControlVariableConflict {
            get {
                return ResourceManager.GetString("LoopControlVariableConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No overload for method &apos;{0}&apos; takes {1} arguments..
        /// </summary>
        internal static string MethodOverloadResolutionFailure {
            get {
                return ResourceManager.GetString("MethodOverloadResolutionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quoted file name, single-line comment or end-of-line expected..
        /// </summary>
        internal static string MissingPreprocessorFile {
            get {
                return ResourceManager.GetString("MissingPreprocessorFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough actual parameters for macro &apos;{0}&apos;..
        /// </summary>
        internal static string NotEnoughMacroParameters {
            get {
                return ResourceManager.GetString("NotEnoughMacroParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword &apos;void&apos; cannot be used in this context..
        /// </summary>
        internal static string NoVoidHere {
            get {
                return ResourceManager.GetString("NoVoidHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameter type &apos;void&apos;..
        /// </summary>
        internal static string NoVoidParameter {
            get {
                return ResourceManager.GetString("NoVoidParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number &apos;{0}&apos; is too large..
        /// </summary>
        internal static string NumberTooLarge {
            get {
                return ResourceManager.GetString("NumberTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since &apos;{0}&apos; returns void, a return keyword must not be followed by an object expression..
        /// </summary>
        internal static string RetNoObjectRequired {
            get {
                return ResourceManager.GetString("RetNoObjectRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An object of a type convertible to &apos;{0}&apos; is required..
        /// </summary>
        internal static string RetObjectRequired {
            get {
                return ResourceManager.GetString("RetObjectRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;: not all code paths return a value..
        /// </summary>
        internal static string ReturnExpected {
            get {
                return ResourceManager.GetString("ReturnExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redefinition of &apos;{0}&apos;..
        /// </summary>
        internal static string SymbolRedefined {
            get {
                return ResourceManager.GetString("SymbolRedefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found &apos;{0}&apos; but expected &apos;{1}&apos;..
        /// </summary>
        internal static string TokenExpected {
            get {
                return ResourceManager.GetString("TokenExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found &apos;{0}&apos; but expected one of the following: {1}..
        /// </summary>
        internal static string TokenExpectedMultipleChoices {
            get {
                return ResourceManager.GetString("TokenExpectedMultipleChoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected token &apos;{0}&apos;..
        /// </summary>
        internal static string TokenUnexpected {
            get {
                return ResourceManager.GetString("TokenUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type expected..
        /// </summary>
        internal static string TypeExpected {
            get {
                return ResourceManager.GetString("TypeExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; does not have a field &apos;{1}&apos;..
        /// </summary>
        internal static string UndeclaredField {
            get {
                return ResourceManager.GetString("UndeclaredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function &apos;{0}({1})&apos; is not declared..
        /// </summary>
        internal static string UndeclaredFunction {
            get {
                return ResourceManager.GetString("UndeclaredFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace or class {0} does not contain a function or method &apos;{1}&apos;..
        /// </summary>
        internal static string UndeclaredFunctionInNamespaceOrClass {
            get {
                return ResourceManager.GetString("UndeclaredFunctionInNamespaceOrClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; does not have an indexer &apos;[{1}]&apos;..
        /// </summary>
        internal static string UndeclaredIndexer {
            get {
                return ResourceManager.GetString("UndeclaredIndexer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; does not have a method &apos;{1}({2})&apos;..
        /// </summary>
        internal static string UndeclaredMethod {
            get {
                return ResourceManager.GetString("UndeclaredMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A namespace or class &apos;{0}&apos; is not declared..
        /// </summary>
        internal static string UndeclaredNamespaceOrType {
            get {
                return ResourceManager.GetString("UndeclaredNamespaceOrType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot resolve type: &apos;{0}&apos;..
        /// </summary>
        internal static string UndeclaredType {
            get {
                return ResourceManager.GetString("UndeclaredType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable &apos;{0}&apos; is not declared..
        /// </summary>
        internal static string UndeclaredVariable {
            get {
                return ResourceManager.GetString("UndeclaredVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute not expected in this context..
        /// </summary>
        internal static string UnexpectedAttribute {
            get {
                return ResourceManager.GetString("UnexpectedAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected directive: &apos;{0}&apos;..
        /// </summary>
        internal static string UnexpectedDirective {
            get {
                return ResourceManager.GetString("UnexpectedDirective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment is not properly terminated..
        /// </summary>
        internal static string UnterminatedComment {
            get {
                return ResourceManager.GetString("UnterminatedComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String is not properly terminated..
        /// </summary>
        internal static string UnterminatedString {
            get {
                return ResourceManager.GetString("UnterminatedString", resourceCulture);
            }
        }
    }
}
