using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("ShaderTools.CodeAnalysis.EditorFeatures")]
[assembly: InternalsVisibleTo("ShaderTools.CodeAnalysis.EditorFeatures.Text")]
[assembly: InternalsVisibleTo("ShaderTools.CodeAnalysis.Features")]
[assembly: InternalsVisibleTo("ShaderTools.CodeAnalysis.Hlsl.EditorFeatures")]
[assembly: InternalsVisibleTo("ShaderTools.CodeAnalysis.Hlsl.Features")]
[assembly: InternalsVisibleTo("ShaderTools.CodeAnalysis.Hlsl.Workspaces")]
[assembly: InternalsVisibleTo("ShaderTools.CodeAnalysis.ShaderLab.EditorFeatures")]
[assembly: InternalsVisibleTo("ShaderTools.CodeAnalysis.ShaderLab.Workspaces")]
[assembly: InternalsVisibleTo("ShaderTools.CodeAnalysis.Workspaces.Desktop")]
[assembly: InternalsVisibleTo("ShaderTools.Editor.VisualStudio")]
[assembly: InternalsVisibleTo("ShaderTools.Editor.VisualStudio.Tests")]
[assembly: InternalsVisibleTo("ShaderTools.LanguageServer")]
[assembly: InternalsVisibleTo("ShaderTools.VisualStudio.LanguageServices")]
[assembly: InternalsVisibleTo("ShaderTools.VisualStudio.LanguageServices.Hlsl")]
[assembly: InternalsVisibleTo("ShaderTools.VisualStudio.SyntaxVisualizer")]